### ISSUE TITLE
PTMShepherd claims 0 scans in a file

### ISSUE THREAD

**Issue by stuomiva** [Nesvilab/PTM-Shepherd#1]
Hey PTMShepherd developers (and users),

First, thanks for your efforts in protemics software development, very eager to try my hands on MSFragger and other software from the NesviLab!

I encountered the following error when analyzing data from Thermo QE using FragPipe GUI (open search, MSFragger, PeptideProphet ProteinProphet, Crystal-C, PTMShepherd all enabled, afaik all newest versions). Partial FragPipe analysis log pasted below, full log attached.
Everything seems to go well until PTMShepherd step, see last few lines of the log.
Both MaxQuant and MetaMorpheus analyze the same raw files without problems.  Used ThermoRawFileParserGUI 3.3.17 to make indexed mzML files for FragPipe from the raw files.  After first failure, redid the mzML generation to rule out file corruption, the problem persists.
What could cause this behaviour?
Thanks for your help!

[FragPipeLogError.txt](https://github.com/Nesvilab/PTM-Shepherd/files/4453413/FragPipeLogError.txt)

System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_241, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 12.2
MSFragger version 2.3
Philosopher version 3.2.3 (build 1583959175)

...

ReportAbacus [Work dir: C:\Users\MassSpec\Desktop\Lab\Project\RawData\FragPipe]
C:\Users\MassSpec\AppData\Local\NesviLab\Philosopher 3.2.3\philosopher.exe abacus --razor --reprint --tag rev_ --protein --peptide 5h_17 50min_15 20hC_7 15min_6 20h_10 20hC_11 0min_1 50min_14 5h_16 50min_13 20h_8 0min_2 20h_12 15min_4 20hC_9 15min_5 5h_18 0min_3
INFO[15:57:06] Executing Abacus v3.2.3                      
INFO[15:57:06] Processing combined file                     
INFO[15:58:23] Converged to 1.00 % FDR with 436792 PSMs      decoy=4409 threshold=0.0776693 total=441201
INFO[15:58:23] Converged to 1.00 % FDR with 32213 Peptides   decoy=325 threshold=0.715185 total=32538
INFO[15:58:23] Restoring peptide results                    
INFO[15:58:43] Collecting data from individual experiments  
INFO[15:58:44] Processing spectral counts                   
INFO[15:58:45] Processing intensities                       
INFO[15:58:47] Processing combined file                     
INFO[15:58:51] Converged to 1.05 % FDR with 2105 Proteins    decoy=22 threshold=0.9956 total=2127
INFO[15:58:52] Restoring protein results                    
INFO[16:00:36] Processing spectral counts                   
INFO[16:01:07] Processing intensities                       
INFO[16:01:11] Creating Reprint reports                     
INFO[16:01:11] Done                                         
Process 'ReportAbacus' finished, exit code: 0

PTMShepherd [Work dir: C:\Users\MassSpec\Desktop\Lab\Project\RawData\FragPipe]
java -Dbatmass.io.libs.thermo.dir="C:\Users\MassSpec\AppData\Local\NesviLab\MSFragger-2.3\ext\thermo" -cp "C:\Users\MassSpec\AppData\Local\Temp\fragpipe\batmass-io-1.17.2.jar;C:\Users\MassSpec\AppData\Local\Temp\fragpipe\commons-math3-3.6.1.jar;C:\Users\MassSpec\AppData\Local\Temp\fragpipe\ptmshepherd-0.2.16.jar" edu.umich.andykong.ptmshepherd.PTMShepherd "C:\Users\MassSpec\Desktop\Lab\Project\RawData\FragPipe\shepherd.config"
PTM-Shepherd version 0.2.16(c) University of Michigan

Using Java 1.8.0_241 on 5461MB memory

Deleted file: C:\Users\MassSpec\Desktop\Lab\Project\RawData\FragPipe\0min_1.ms2counts
Unrecognized extension: raw
Fatal error: Invalid MS2 counts for run 0min-b1-t1-Pre-inf in dataset 0min_1
Counting MS2 scans for dataset 0min_1
	0min-b1-t1-Pre-inf - 0 scans
Process 'PTMShepherd' finished, exit code: 1

Process returned non-zero exit code, stopping
SpecLibGen
java -cp C:\Users\MassSpec\AppData\Local\NesviLab\FragPipe\FragPipe.exe umich.msfragger.util.FileCopy C:\Users\MassSpec\Desktop\Lab\Project\RawData\5h-b2-t1-Inf.mzML C:\Users\MassSpec\Desktop\Lab\Project\RawData\FragPipe\5h_17\5h-b2-t1-Inf.mzML

~~~~~~~~~~~~~~~~~~~~
Cancelling 73 remaining tasks
Processing interrupted, stopping SpecLibGen

**Comment by danielgeiszler** [comment]
Hey Stuomiva,

It looks like it tried to read your raw file instead of your mzML and broke because it can’t read raw files. This is fixed in the current version and will be pushed out with the next release of Fragpipe. If you can’t wait for that, I believe a quick fix in the meantime should be moving your raw files into a different directory or adding a prefix to them so they makes don’t match the file names in the psm.tsv output. 

Once you do that, you should be able to restart your fragpipe process from PTM-Shepherd by unchecking everything else.

Sorry for the inconvenience. Please let us know if that works!

**Comment by stuomiva** [comment]
Hi,

Thanks for your reply!  I moved the raw files to a different location and now the analysis proceeds just fine.  Thanks again for your quick help!

S

**Comment by danielgeiszler** [comment]
Excellent. Closing this issue.
