### ISSUE TITLE
Interpratation of PTM shephard global PTM results

### ISSUE THREAD

**Issue by okendojo** [Nesvilab/PTM-Shepherd#10]
I have done the PTM analysis on the open search results using MSfragger. I am struggling to make sense of the results. Could you help in making sense of the Enrichment columns? The relationship between peakApex and the matched PSMs. Any pointer will be appreciated.

![Screenshot from 2020-10-30 10-50-42](https://user-images.githubusercontent.com/26459707/97679701-45045980-1a9e-11eb-979f-b238158c92eb.png)

**Comment by danielgeiszler** [comment]
Hi Javan,

Matched PSMs is the number of PSMs corresponding to the mass shift. The mass shift is the peak apex.
