### ISSUE TITLE
In a DDA search open mass search, how would any masses not matched to Unimod be reported?

### ISSUE THREAD

**Issue by juank1892** [Nesvilab/PTM-Shepherd#11]

**Comment by danielgeiszler** [comment]
Hi juank, when we talked before I think you wanted a version that mapped all masses to unimod regardless of whether or not they were included within PTM-Shepherd profile results (i.e., not within a PTM-Shepherd peak), correct? I have an experimental version that can do this now if you're interested.

**Comment by juank1892** [comment]
Hi Daniel,

I don't expect some of my modifications to be in unimod because I deal with derivatized adducts that have not been added to the unimod database and some of them are expected to be "new" PTM discoveries. However, if I was able to obtain the mass shifts reported in the "global.summary.tsv" or "modifications.tsv" mapped to a specific peptide (and ideally amino acid) in the PSM output, it would be very helpful for manual confirmation.

If the experimental version is able to perform this request I would be very interested in testing it!

JC

PS: if my e-mail is need to share the exp. version you can use the following:
juan_camilo.rojas_echeverri@uni-leipzig.de

**Comment by danielgeiszler** [comment]
Hi Juan,

You can drop this into your fragpipe/tools folder. It's still pre-release. I'm not sure how it will work if you have both the old and new versions on there, so try deleting the old one.

If PTM-Shepherd finds a cluster of mass shifts (your adducts), it will create a peak called "Unannotated mass shift of XXX Da". Then it map that annotation back into the filtered psm.tsv table. It will also annotate any mass shifts found in unimod but not abundant enough for PTM-Shepherd to find a peak.

It still can't map them to a particular amino acid easily, but I think that some other software is doing that in our next release in a couple weeks. I'm assuming you're doing an open or mass offset search, in which case the localizations can be found in $SPECNAME.tsv, but will need to be mapped back manually for now, unfortunately.

https://www.dropbox.com/sh/19qsmurhyxendts/AADuMvQEwBJWrt3nObiwBlT3a?dl=0

Let me know how it works!
