### ISSUE TITLE
Questions for PTM-Shepherd running

### ISSUE THREAD

**Issue by YSosu** [Nesvilab/PTM-Shepherd#12]
Dear All,

I was analyzing tims tof pro data with MS Fragger, But I forgot to turn PTM-Shepherd on. So I want to run it with standalone mode.
My question is when we are building config file it does required to add the directory for MZML file. In this case, Do I have to put the location of the raw data? or Either MGF or MZBINE files generated from MS Fragger?

Thanks,

**Comment by fcyu** [comment]
You can uncheck all other tools in FragPipe to make it only run PTM-Shepherd, which, I think, it the easiest way.

Best,

Fengchao

**Comment by YSosu** [comment]
Thanks, however, It says "Fatal error: In data set "q" could not find mzData for run XXXX. 
Does it say that because I have space in the directory of my file?

**Comment by YSosu** [comment]
I solved the problem by relocating the datafile to where there was no space in the directory

Thanks
