### ISSUE TITLE
FragPipe results

### ISSUE THREAD

**Issue by MartinaBartolucci** [Nesvilab/PTM-Shepherd#14]
Hello,

in the global.profile file released by Offset search for PTMs with FragPipe I can't understand the meaning of the column [experiment] _percent_also_in_unmodified, can you clarify what the reported data means?
Thanks for the attention.
Martina

**Comment by sarah-haynes** [comment]
Hi Martina, we have descriptions of FragPipe output files [here](https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html), see global.profile.tsv [here](https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#globalprofiletsv).

Sarah

**Comment by MartinaBartolucci** [comment]
Thanks, unfortunately I have already read those and I do not understand the percentage to what it refers. Can I use this parameter as a comparison between mutated and not?

**Comment by danielgeiszler** [comment]
Hi Martina,

Can you elaborate on what it is you're doing? The mass offset search is not designed to look for mutations, it's designed to look for PTMs.

This column is simply the percentage of PSMs with that PTM that has a corresponding unmodified PSM.

**Comment by MartinaBartolucci** [comment]
Sorry, modified, not mutated. I have 4 groups of samples and I need to see if there are any proteins with modifications due to the A to I editing of the RNA. I calculated all the mass differences of the possible amino acid substitutions and used them for the offset search. Now among the results of the offset search I would like to understand which is the best parameter that allows me to compare the different groups of samples. 
Thanks again.

**Comment by danielgeiszler** [comment]
The [experiment] _percent_also_in_unmodified column is telling you how many modified PSMs **within that group** have a matched unmodified PSM. 

If you're looking to compare the number of mutations **between** groups, then you'd probably just want to use the PSM counts or the [experiment]_percent PSMs themselves.
