### ISSUE TITLE
global.profile.tsv - missing delimiter?

### ISSUE THREAD

**Issue by JosieAC** [Nesvilab/PTM-Shepherd#15]
In PTM-Shepherd with FragPipe, I have noticed the **global.profile.tsv** may be missing a delimiter, which is causing the columns to shift to the right one position when I read this into R. May be an issue on my end but thought I would bring this minor issue up, in case you can replicate the issue yourselves. 

See below results when using `count.fields()` to tally the delimiters of two example **global.profile.tsv** files:

```
> table(count.fields(paste0(project_path, "data/OpenSearch__FragPipe/global.profile.tsv"), sep = "\t"))

118 119 
  1 168 
> table(count.fields(paste0(project_path, "data/OpenSearch__FragPipe/old_run/global.profile.tsv"), sep = "\t"))

 26  27 
  1 176 
```

Seems to be in the first column:
```
> count.fields(paste0(project_path, "data/OpenSearch__FragPipe/global.profile.tsv"), sep = "\t")

  [1] 118 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119
 [30] 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119
 [59] 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119
 [88] 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119
[117] 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119
[146] 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119 119

```

This appears to be exclusive to this file, as the **global.modsummary.tsv** files seem fine:

```
> table(count.fields(paste0(project_path, "data/OpenSearch__FragPipe/old_run/global.modsummary.tsv"), sep = "\t"))

  4 
103 

> table(count.fields(paste0(project_path, "data/OpenSearch__FragPipe/global.modsummary.tsv"), sep = "\t"))

 50 
112 

```

[shepherd.txt](https://github.com/Nesvilab/PTM-Shepherd/files/9723953/shepherd.txt)

* FragPipe v18.0
* IonQuant 1.8.0
* MSFragger 3.5
* Philosopher v4.4.0

**Comment by danielgeiszler** [comment]
Can you please zip and upload your global profile table here? My tables align properly.

**Comment by JosieAC** [comment]
[global.profile.zip](https://github.com/Nesvilab/PTM-Shepherd/files/9755727/global.profile.zip)

**Comment by danielgeiszler** [comment]
Sorry for not getting back to you on this. This is probably too late to be of use to you now, but it may be useful in the future.

There is no issue in PTM-Shepherd.

If you open it in Excel, eveyrthing aligns. The issue is probably how it gets converted into a dataframe because the first colum is numeric. Sometimes it will try to read that column as the index.
