### ISSUE TITLE
Questions for modifications in the "psm.tsv" file

### ISSUE THREAD

**Issue by Kadewhilingtz** [Nesvilab/PTM-Shepherd#16]
Hello!
We are doing open search for  the TMT data. When checking the "psm.tsv" file,  we have some quesetions:

1. We understand "PeakApex" as the mass shift detected for that psm, and "Theoretical" as the theoretical mass of the modification for which that mass shift was matched in the UNIMOD database. Why do some modifications have both "PeakApex" and "Theoretical" and some have only one?
![图片](https://github.com/Nesvilab/PTM-Shepherd/assets/75680807/70cc7a4d-1d69-4294-9bbf-ff500b40cda9)
![图片](https://github.com/Nesvilab/PTM-Shepherd/assets/75680807/2af07fc8-55c1-4665-a24b-8711170ad5ff)

2. Modifications are the same, but the PeakApex is different. 
For example, the delta mass of a PSM is 13.004 and the Observed Modifications are: Mod1: Loss of O2; nitro photochemical decomposition (PeakApex: 12.9954, Theoretical: 12.9952) ; Mod1: Loss of O2; nitro photochemical decomposition (PeakApex: 13.0032). Here for two identical modification combinations possible, why is PeakApex different.

4. Many PSMs have a large delta mass, but do not show the modification.
In the figure below, the red box shows a large delta mass, but no modification is matched. Why is it that such a large delta mass exists and no modification is identified, but it is counted as a match.
![图片](https://github.com/Nesvilab/PTM-Shepherd/assets/75680807/c33b0e28-a328-4776-8c0a-d2e05b9c9983)

Best,
Ling.

**Comment by danielgeiszler** [comment]
Duplicate, answered in the FragPipe repository.
