### ISSUE TITLE
array index out of bounds exception

### ISSUE THREAD

**Issue by jgmeyerucsd** [Nesvilab/PTM-Shepherd#2]
I'm running the full fragpipe analysis on my data and when it gets to PTM-shephard it fails. I've attached the log and config files. Here is the error text in fragpipe:

Creating combined histogram
	Generated histogram file for dataset Control_1 [-154 - 498]
	Generated histogram file for dataset Control_2 [-155 - 502]
	Generated histogram file for dataset Control_3 [-152 - 500]
	Generated histogram file for dataset Control_4 [-153 - 504]
	Generated histogram file for dataset Control_5 [-154 - 504]
	Generated histogram file for dataset EtOH_1 [-154 - 502]
	Generated histogram file for dataset EtOH_2 [-154 - 503]
	Generated histogram file for dataset EtOH_3 [-153 - 496]
	Generated histogram file for dataset EtOH_4 [-154 - 503]
	Generated histogram file for dataset EtOH_5 [-153 - 498]
	Generated histogram file for dataset LPS_1 [-151 - 502]
	Generated histogram file for dataset LPS_2 [-154 - 502]
	Generated histogram file for dataset LPS_3 [-151 - 503]
	Generated histogram file for dataset LPS_4 [-151 - 500]
	Generated histogram file for dataset LPS_5 [-151 - 502]
Created combined histogram!

Running peak picking

Picked top 500 peaks

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at edu.umich.andykong.ptmshepherd.peakpicker.PeakAnnotator.init(PeakAnnotator.java:192)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:328)
created summary table
[log-fragpipe-run-at_2020-04-28_12-22-23.log](https://github.com/Nesvilab/PTM-Shepherd/files/4551633/log-fragpipe-run-at_2020-04-28_12-22-23.log)
[ptm-shepherd.log](https://github.com/Nesvilab/PTM-Shepherd/files/4551634/ptm-shepherd.log)

[fragpipe_2020-04-28_09-53-26.config.txt](https://github.com/Nesvilab/PTM-Shepherd/files/4551636/fragpipe_2020-04-28_09-53-26.config.txt)
[shepherd.config.txt](https://github.com/Nesvilab/PTM-Shepherd/files/4551637/shepherd.config.txt)

**Comment by danielgeiszler** [comment]
Hi @jgmeyerucsd,

Sorry for the late reply. This is fixed in the most recent version, but for now I believe you should be able to replace the varmod_masses parameter which is causing it to break with the default by clicking on the "Load Shepherd Defaults" button, or placing None:0 in the Custom Mass Shifts line in the PTMShepherd tab in the GUI.

Let me know if that works.

**Comment by danielgeiszler** [comment]
No response.
