### ISSUE TITLE
MSFragger (windows), non-zero exit code, stopping

### ISSUE THREAD

**Issue by liujiangf09** [Nesvilab/PTM-Shepherd#3]
Hi,
I want to use MSFragger to perform open search. But it report 'non-zero exit code, stopping' error. I have provided the screenshot of error reporting.

No error was reported when I do closed search or open search of TMT proteome. However, all the open search for label-free proteome was interrupted.

Look forward to your reply.

![Error_report](https://user-images.githubusercontent.com/54832383/81491692-b91a2d80-92c3-11ea-8df1-dd3c85d37db1.jpg)

**Comment by danielgeiszler** [comment]
Hi @liujiangf09 

Are you trying to run PTMShepherd on raw data? The released version of PTMShepherd does not support raw data files. However, the deveopment version does and this feature will be enabled with the next fragpipe release.

**Comment by liujiangf09** [comment]
Hi~
I converted the .raw files into .mzxml files (detached below). I did closed search and the results seemed fine. I did open search with TMT .mzxml files (converted from .raw files using the same parameters), and no errors was reported (but the results are unreasonable). 
Does it mean that open search need PTMShepherd and closed search do not need it?
Thank you for your reply.

![msconverter_parameter](https://user-images.githubusercontent.com/54832383/81519898-44073080-9375-11ea-9b4e-28965f45c852.jpg)

**Comment by liujiangf09** [comment]
I will attach the error report picture again. It seems that the first picture was not successfully uploaded.
![Error_report](https://user-images.githubusercontent.com/54832383/81520205-38683980-9376-11ea-8ca6-b51bd72cfb56.jpg)

**Comment by fcyu** [comment]
Hi @liujiangf09 ,

Open search results (`psm.tsv`, `peptide.tsv`, `ion.tsv`, `protein.tsv`, and ect) don't dependent on PTMShepherd. PTMShepherd is a post-processing tool summarizing modifications from open searh.

Could you please elaborate a little bit more regarding "the results are unreasonable"? Log files, result tables, and data are also helpful.

Thanks,

Fengchao

**Comment by liujiangf09** [comment]
Hi~
Details of my questions about the TMT proteome are listed in the following issue.

https://github.com/Nesvilab/MSFragger/issues/61

If more details are needed, I will try my best to provide. As I said in the issue, I was shocked when I received the question at first. But then I made a lot of effort and I am interested in the answer.

Thank you.

**Comment by fcyu** [comment]
HI @liujiangf09 ,

I checked your parameters, I think the variable modification for open search should be 
```
variable_mod_01 = 15.99490 M 3
variable_mod_02 = 42.01060 [^ 1
# variable_mod_03 = 79.96633 STY 3
# variable_mod_04 = -17.02650 nQnC 1
variable_mod_05 = 229.16290 K 1
variable_mod_06 = 229.16290 n^ 1
# variable_mod_07 = 68.02300 K 3
```

Unfortunately, none of your files has this setting. Can you try it and let me know the result?

Best,

Fengchao

**Comment by danielgeiszler** [comment]
@liujiangf09 

This may not resolve your PTMShepherd issue. You may have to remove the raw files from the directory in order to process them due to a bug in the released version of PTMShepherd

**Comment by liujiangf09** [comment]
@fcyu @danielgeiszler 
I think your suggestions work!
I use the suggested parameters for TMT crotonylome, and 8,085 peptides are identified (peptide.tsv). I attach the global.modsummary.tsv file below.
Then, I remove the raw files from the directory, and I can get the global.modsummary.tsv file for label-free dataset now.

Would you like to tell me how to calculate the percentage of each modification identified by open search? I don't think I have understood the 'default-ptmshepherd-datasets' well. So I do not know how to set the numerator and the denominator.

Thank you!

Best regards
[global.modsummary_TMT.xlsx](https://github.com/Nesvilab/PTM-Shepherd/files/4614778/global.modsummary_TMT.xlsx)

**Comment by danielgeiszler** [comment]
Hi @liujiangf09 

The 'default-ptmshepherd-dataset' is the name of the dataset you processed. If you didn't fill one in, then it the just the default name assigned to your dataset.

In the global.modsummary.tsv table, the PSMs column correspond to the number of times your modification was identified. However, if we identified a mass shift that was, for example, TMT + crotonylation, any PSMs with that mass shift will be added to both the 'crotonylation' row and the 'TMT 6-plex' row in the global.modsummary.tsv table.

The global.modsummary.tsv tends to gives a better picture of the total amount of your modification in your sample, but can be less precise because it is combining multiple mass shifts.

If you just want the number corresponding to the crotonylation mass shift and nothing else, you can find that number in the global.profile.tsv. This will be the number of PSMs in your dataset with that specific mass shift.

**Comment by liujiangf09** [comment]
Thank you for your answer.
At last, I want to know whether I can provide this github link in my Response to Comments letter. I look foward to your permission.

**Comment by danielgeiszler** [comment]
Hi @liujiangf09 

You can refer to the PTM-Shepherd wiki page in the repositiory for your response.

**Comment by liujiangf09** [comment]
Thank you!
