### ISSUE TITLE
Making sense of the PTM-shephard results

### ISSUE THREAD

**Issue by okendojo** [Nesvilab/PTM-Shepherd#6]
Hi all,
I know this may be a spammy question but I am genuinly asking for your help in the interpratation of the PTM shephard result. I have a problem making sense of the output PTM profile text file (see the attached file). Which column should I use in interprating the PTMs in my data? should I use the enrichment column or the mass shift column? Kindly help
[$SIM_bcg.profile.txt](https://github.com/Nesvilab/PTM-Shepherd/files/5191239/SIM_bcg.profile.txt)

**Comment by danielgeiszler** [comment]
For future reference, please see the output file list and descriptions here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html
