### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/PTM-Shepherd#7]
Dear all,

I tried to use PTM-Shepherd to analyze the modification pattern from one psm.tsv which I split into two separate files (each containing a subset of my proteins) to find differences in the modification pattern between the two groups.
However, during the localization annotation step the following error occurs several times:

![200914_PTMShepherd_Error](https://user-images.githubusercontent.com/51822132/93105899-e3d02480-f6af-11ea-8d69-f842b72a18fb.PNG)

**Comment by danielgeiszler** [comment]
Can you try running this on the original psm.tsv as well to see if the same error occurs?

**Comment by JB91451** [comment]
Yes, I will run this over night and inform you tomorrow about the results.

**Comment by JB91451** [comment]
Dear Daniel,

with the original psm.tsv it run through completely.

**Comment by danielgeiszler** [comment]
It looks like something is wrong with the pal tables you’re producing. The input is different somehow.

**Comment by JB91451** [comment]
Dear Daniel,

Thank you for the hint. I re-checked the file and realized that the problem was that I removed the absolute path to the interact.pep.xml file (I had to move it to a different computer and used the update-paths script from the TPP prior running philosopher) from the report.
Adding the complete path in the psm.tsv solved the problem.

Thank you again,
Juergen
