### ISSUE TITLE
questions on global.profile.tsv output

### ISSUE THREAD

**Issue by Morder86** [Nesvilab/PTM-Shepherd#9]
Hi,

I am trying to evaluate the extent of peptide modifications in my sample using the open search with MSFragger and PTM-Shepherd. There are couple of things that do not make much sense to me, and I would be grateful if someone could explain them:

1. I have analyzed two samples, so for each peak in global.profile.tsv I have Matched.PSMs value, as well values for PSMs in individual samples (X16..PSMs. and X17..PSMs. in my case). My understanding is that Matched.PSMs should be a sum of PSMs in the individual samples. In most cases this is true, but for some peaks the value is different from this sum. Why is that?

2. When I summarize the PSMs from the columns for the individual samples (X16..PSMs and X17..PSMs), I expect to have the same number of PSMs as I have in the individual psm.tsv files for each of my samples. In reality, the sum of PSMs from global.profile.tsv file for each sample is less then number of PSMs in the psm.tsv files for the same samples.  Why is that?

I have attached my global.profile.tsv file here. 

[global.profile.xlsx](https://github.com/Nesvilab/PTM-Shepherd/files/5307998/global.profile.xlsx)

**Comment by danielgeiszler** [comment]
Hi Morder. Sorry for the late reply, this slipped through the cracks. If you haven't seen already, it is because only PSMs matching to a mass shift peak found by PTM-Shepherd are included in that table. Those not matching to a mass shift peak are not included in the table.
